### ISSUE TITLE
Problem plugin

### ISSUE THREAD

**Issue by jdecampos** [kuzmany/mautic-prestashop#2]
Hi Kuzmany,
I use prestashop 1.7.2 and I encounter a bug.
I have an empty error header, my different voids.
When I activate the bug mode, I have these errors.
Bes regards,
<img width="1449" alt="capture d ecran 2017-07-30 a 12 50 02" src="https://user-images.githubusercontent.com/14194414/28752704-30930d78-7526-11e7-9190-4940d70d8ed4.png">

**Comment by phgeek** [comment]
Hi,
If you are  getting empty lists check out my issue https://github.com/kuzmany/mautic-prestashop/issues/1#issuecomment-341853219
